[env:nucleo_h753zi]
platform = ststm32
board = nucleo_h753zi
framework = stm32cube
upload_protocol = stlink
monitor_speed = 115200
platform_packages =
    platformio/toolchain-gccarmnoneeabi@1.140201.0
lib_deps =
    https://github.com/jesdev-io/jescore.git#e81b78f28210e4fbc67edf53b97a846b7b90bc03
    https://github.com/hathach/tinyusb.git#0.21.0
lib_ignore =
    *
    !tinyusb_audio_h753zi
build_flags =
    -mfloat-abi=hard
    -mfpu=fpv5-d16
    -DCFG_TUSB_MCU=OPT_MCU_STM32H7
    -DBOARD_TUD_RHPORT=0
    -DBOARD_TUD_MAX_SPEED=OPT_MODE_FULL_SPEED
    -DCFG_TUSB_DEBUG=0
    -Iinclude
    -Ilib/tinyusb_audio_h753zi
    -I$PROJECT_PACKAGES_DIR/framework-stm32cubeh7/Middlewares/Third_Party/FreeRTOS/Source/include
    -I$PROJECT_PACKAGES_DIR/framework-stm32cubeh7/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1
    -I.pio/libdeps/$PIOENV/jescore/include/FreeRTOSConfig
    -I.pio/libdeps/$PIOENV/jescore/include
    -Wno-error=implicit-function-declaration
