[project]
name = "ssstm32"
version = "0.1.0"
description = "State Space Model Driver for the STM32 Platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyfar",
    "platformio>=6.1.19",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]

[tool.uv.sources]
pyfar = { git = "https://github.com/pyfar/pyfar", rev = "fd33a589807f75ef238c5ac7f6436276eb4503e3" }


[tool.basedpyright]
venv = ".venv"
typeCheckingMode = 'off'


[tool.ruff]
src = ["src"]
line-length = 120

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = ["B", "D", "E", "F", "I", "ICN", "N", "Q", "W"]
ignore = [
    "D100", "D101", "D102", "D103", "D104", "D401",
    "E741",
    "N802", "N803", "N806",
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 100

[tool.ruff.lint.pydocstyle]
convention = "numpy"
